### ISSUE TITLE
Changes required to mineable terrains

### ISSUE THREAD

**Issue by ZhilkinSerg** [DangerNoodle/mining-mod#16]
Mineable terrains need to be updated - see https://github.com/CleverRaven/Cataclysm-DDA/issues/25225 and https://github.com/CleverRaven/Cataclysm-DDA/pull/24787

**Comment by DangerNoodle** [comment]
Thank you for that. https://github.com/DangerNoodle/mining-mod/commit/ca4420d8b4ffbcfb8e0ebcac11e9502353ffebf0 should resolve this.

I discovered that using `copy-from` to attempt to streamline the `t_rock` change caused load errors, so for now I have simply removed the override entirely, as maintaining a full override will risk events like this occurring again in the future.

Due to vanilla solid rock yielding rock salt and coal, I also changed the bituminous coal and halite terrains to yield their contents at a 100% rate.

Thank you, and please inform me if I missed anything of note.
