### ISSUE TITLE
Unrecognized JSON object Line 3:12

### ISSUE THREAD

**Issue by ShiroiOkami11** [DangerNoodle/mining-mod#36]
[
 {
  "type": "construction_group",
  "id": "make_stone_anvil",
  "name": "Make Stone Anvil"

FUNCTION: bool_main_menu::new_character_tab() 
FILE: src/main_menu.cpp
LINE: 887

**Comment by chaosvolt** [comment]
Use the correct version if possible. If using DDA, use the Mining_Mod folder. If using Bright Nights, use the 

Unfortunately never got the time to help set aside a release for 0.E stable for DN, so if you're using 0.D Stable or 0.E Stable none of the available versions will work for you, and a lot has changed given how long it's been.

0.F Stable is supposed to be out one of these days, but alternatively I would strongly suggest seeing if the Bright Nights fork is more to your liking, if you've been sticking with DDA stable build due to any of the notable unfinished changes in experimental builds: https://github.com/cataclysmbnteam/Cataclysm-BN
