### ISSUE TITLE
Have the recent overmap improvements affected Mining Mod in any way?

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [DangerNoodle/mining-mod#6]

**Comment by DangerNoodle** [comment]
My apologies, I would need to see which you mean, and test them. What changes are to be expected?

**Comment by DangerNoodle** [comment]
Finally had the opportunity to test this. So far it seems to function. However, I stress tested the system by combining this mod with Arcana and Magic Items, More Locations, Urban Development, PK's Rebalance, National Guard Camp, and Cataclysm++. I found that rather than reporting a "too many specials" error as before, it was hang up during the "finalizing and verifying" step.

![demonstration](https://user-images.githubusercontent.com/22048567/29984441-16f28038-8f20-11e7-9f5f-fe3b7986c60a.png)

To confirm that it was not a mod interaction issue, and after confirming my mod still works by itself without issue, I deliberately set the minimum specials for Mining Mod to a point that would exceed the mandatory specials limit, and found the same issue of it being stuck at the finalizing screen rather than crashing or generating an error message.

Pinging @Coolthulhu as they might not be aware of this problem.

**Comment by chaosvolt** [comment]
Huh. Just found this. Yeah that's definitely a regression, someone needs to report that as an issue in CDDA, as fucked if I know whether they'll see it here.

Honestly that sounds like the exact opposite of an improvement. Doesn't allow bumping map specials up any higher than what it is now, and worsens symptoms of overmap-overdose because the thing telling you it broke doesn't show.

@BorkBorkGoesTheCode, does Urban Development have some magic in it that lets it not affect the mandatory specials limit? I looked at it and couldn't figure out what's keeping it from being as problematic as More Locations.

**Comment by Coolthulhu** [comment]
I am not aware of any changes that would break the mod totally. There has been a big change to overmapgen that could make special overpopulation work differently, though.
Try those to verify:
* Wait a longer while on finalization screen (could be just long delay)
* Mash 'i' a few times on that finalization screen (after waiting), to make sure it's not some skipped debug message
* Try loading an existing save with world generated, to check whether this is finalization or overmapgen

**Comment by chaosvolt** [comment]
Second one is still a bug if error messages aren't displaying, and I don't see how the third would be even possible to test, if the total map specials are above the threshold for it to freak out.

**Comment by DangerNoodle** [comment]
Will test delay. A long finalization time is expected, but uncertain how long would be a reasonable point to assume a bug has ensued.

Note that deliberately exceeding the maximum mandatory specials with only a single non-default mod caused the same effect, when a prompt loading time would be expected in this scenario.

**Comment by DangerNoodle** [comment]
> and I don't see how the third would be even possible to test

Would generating a world below this threshold, saving a character, increasing mandatory specials beyond the limit, then attempting to load qualify as a test of this?

**Comment by DangerNoodle** [comment]
Started timer when the "finalizing and verifying" message appeared. Ten minutes have passed with no change. Subsequently hit `i` and it went on to the character creation screen.

This seems to confirm that the "too many mandatory specials" message is failing to appear properly, which I agree is a regression.

Note that these tests are on the non-graphical version. Should I additionally test with the tile version?

**Comment by DangerNoodle** [comment]
![breakthrough](https://user-images.githubusercontent.com/22048567/29988200-a25db49c-8f31-11e7-806c-466f03805d01.png)

I can now confirm that this issue does not occur in the graphical version.

Now that Chaosvolt has mentioned it, @Coolthulhu is there any method used by a mod to bypass the overmap special limit? I could have sworn that you once mentioned multiple-story houses in mainline, using a method that adds specials to cities without affecting the limit.

**Comment by Coolthulhu** [comment]
The mandatory special count message does not cancel an attempt to generate the map. It only warns.

> I could have sworn that you once mentioned multiple-story houses in mainline, using a method that adds specials to cities without affecting the limit.

It's not implemented yet and will only work for city buildings.

**Comment by DangerNoodle** [comment]
I see. That said, invisible messages are definitely a problem, given they give the impression that the game is frozen.

**Comment by BorkBorkGoesTheCode** [comment]
>My apologies, I would need to see which you mean, and test them. What changes are to be expected?

This series by codemime:
https://github.com/CleverRaven/Cataclysm-DDA/pull/21620


The invisible error messages in console still haven't been fixed:
https://github.com/CleverRaven/Cataclysm-DDA/issues/20061

**Comment by DangerNoodle** [comment]
I see. So far I have observed nothing major in need of changing. I will need you to keep me informed if anything urgent comes up, due to my being barred from contributing. My apologies.

**Comment by BorkBorkGoesTheCode** [comment]
I found and updated a few deprecated fields in #7 if you're interested.

**Comment by chaosvolt** [comment]
> barred from contributing

Ah yes, that. Sorry to hear. At least when I was barred I was being just as much of a shitheel as Kevin was at the time, but seems to be like you didn't do anywhere near the sort of things that deserved that.

**Comment by DangerNoodle** [comment]
It was my fault. I got frustrated and broke from my usual attempts to remain civil.
